-- University schema filled with valid data

DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS professors;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
  department_id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  building TEXT NOT NULL
);

CREATE TABLE professors (
  professor_id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  department_id INT NOT NULL 
);

CREATE TABLE students (
  student_id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  enrollment_year INT NOT NULL,
  major_department_id INT NOT NULL
);

CREATE TABLE courses (
  course_id SERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  department_id INT NOT NULL,
  professor_id INT NOT NULL,
  credits INT NOT NULL,
  term TEXT NOT NULL,
  year INT NOT NULL
);

CREATE TABLE enrollments (
  enrollment_id SERIAL PRIMARY KEY,
  student_id INT NOT NULL,
  course_id INT NOT NULL,
  enrolled_on DATE NOT NULL,
  status TEXT NOT NULL,
  grade TEXT
);

INSERT INTO departments (name, building) VALUES ('Computer Science', 'Engineering Hall');
INSERT INTO departments (name, building) VALUES ('Mathematics', 'Newton Center');
INSERT INTO departments (name, building) VALUES ('Physics', 'Faraday Building');
INSERT INTO departments (name, building) VALUES ('Biology', 'Darwin Hall');
INSERT INTO departments (name, building) VALUES ('Chemistry', 'Curie Complex');
INSERT INTO departments (name, building) VALUES ('Economics', 'Keynes Hall');
INSERT INTO departments (name, building) VALUES ('History', 'Heritage Hall');
INSERT INTO departments (name, building) VALUES ('Psychology', 'Cognitive Center');
INSERT INTO departments (name, building) VALUES ('English', 'Literature Center');
INSERT INTO departments (name, building) VALUES ('Statistics', 'Gauss Hall');

INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Morgan','Smith','msmith@univ.edu',5);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','White','qwhite@univ.edu',3);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Morgan','Walker','mwalker@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Reagan','Robinson','rrobinson@univ.edu',1);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Alex','Brown','abrown@univ.edu',4);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Lee','qlee@univ.edu',10);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Alex','Walker','awalker@univ.edu',4);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Peyton','Robinson','probinson@univ.edu',4);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Drew','Hall','dhall@univ.edu',5);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Alex','Thomas','athomas@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Parker','Harris','pharris@univ.edu',3);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Avery','Thompson','athompson@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Taylor','Martinez','tmartinez@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Reese','Garcia','rgarcia@univ.edu',10);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Jamie','Johnson','jjohnson@univ.edu',8);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Peyton','Taylor','ptaylor@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Taylor','Walker','twalker@univ.edu',5);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Sage','Garcia','sgarcia@univ.edu',10);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Avery','Brown','abrown2@univ.edu',1);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Martin','qmartin@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Taylor','qtaylor@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Jamie','Clark','jclark@univ.edu',6);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Casey','Garcia','cgarcia@univ.edu',6);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Avery','Harris','aharris@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Sage','Thomas','sthomas@univ.edu',9);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Thomas','qthomas@univ.edu',8);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Rowan','Harris','rharris@univ.edu',9);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Thompson','qthompson@univ.edu',1);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Quinn','Johnson','qjohnson@univ.edu',6);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Rowan','Harris','rharris2@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Avery','Hall','ahall@univ.edu',6);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Avery','Lewis','alewis@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Drew','Anderson','danderson@univ.edu',5);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Riley','White','rwhite@univ.edu',9);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Peyton','Harris','pharris2@univ.edu',10);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Skyler','Hall','shall@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Reese','White','rwhite2@univ.edu',3);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Logan','Lewis','llewis@univ.edu',2);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Jordan','Taylor','jtaylor@univ.edu',3);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Casey','Robinson','crobinson@univ.edu',10);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Taylor','Martinez','tmartinez2@univ.edu',7);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Sage','Clark','sclark@univ.edu',9);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Jamie','Walker','jwalker@univ.edu',1);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Morgan','Walker','mwalker2@univ.edu',5);
INSERT INTO professors (first_name, last_name, email, department_id) VALUES ('Parker','Taylor','ptaylor2@univ.edu',5);

INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Skyler','Thomas','sthomas@univ.edu',2025,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jamie','Lee','jlee@univ.edu',2020,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Morgan','Martin','mmartin@univ.edu',2021,3);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reese','Thomas','rthomas@univ.edu',2018,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Parker','Lewis','plewis@univ.edu',2018,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reese','Martin','rmartin@univ.edu',2021,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','Hall','qhall@univ.edu',2019,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Harper','Brown','hbrown@univ.edu',2020,3);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Harper','Walker','hwalker@univ.edu',2020,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Logan','Allen','lallen@univ.edu',2024,4);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Peyton','Jackson','pjackson@univ.edu',2022,7);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reese','Clark','rclark@univ.edu',2025,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','White','qwhite@univ.edu',2019,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Alex','Hall','ahall@univ.edu',2021,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','Smith','qsmith@univ.edu',2019,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','Brown','qbrown@univ.edu',2018,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Taylor','Lee','tlee@univ.edu',2021,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Harper','Jackson','hjackson@univ.edu',2020,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reagan','Lewis','rlewis@univ.edu',2021,8);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Skyler','Jackson','sjackson@univ.edu',2019,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Skyler','Garcia','sgarcia@univ.edu',2024,7);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Drew','Johnson','djohnson@univ.edu',2019,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Rowan','Thompson','rthompson@univ.edu',2019,4);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Avery','Jackson','ajackson@univ.edu',2025,3);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Skyler','Thomas','sthomas2@univ.edu',2022,8);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','Brown','qbrown2@univ.edu',2025,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Morgan','Johnson','mjohnson@univ.edu',2018,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Quinn','Thomas','qthomas@univ.edu',2024,8);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Harper','Jackson','hjackson2@univ.edu',2024,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Casey','Martinez','cmartinez@univ.edu',2018,7);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jamie','Clark','jclark@univ.edu',2022,7);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Peyton','Lewis','plewis2@univ.edu',2020,4);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Kendall','Jackson','kjackson@univ.edu',2018,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Peyton','Johnson','pjohnson@univ.edu',2023,1);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jordan','Hall','jhall@univ.edu',2025,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Logan','Thomas','lthomas@univ.edu',2018,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Taylor','Thomas','tthomas@univ.edu',2019,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Taylor','White','twhite@univ.edu',2024,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reagan','White','rwhite@univ.edu',2018,10);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Taylor','Robinson','trobinson@univ.edu',2023,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Avery','Thompson','athompson@univ.edu',2021,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Rowan','Anderson','randerson@univ.edu',2022,8);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Parker','Brown','pbrown@univ.edu',2018,8);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Sage','Hall','shall@univ.edu',2019,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Peyton','Jackson','pjackson2@univ.edu',2022,3);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reese','Brown','rbrown@univ.edu',2021,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Kendall','Thomas','kthomas@univ.edu',2025,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Kendall','Allen','kallen@univ.edu',2018,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Kendall','Taylor','ktaylor@univ.edu',2020,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Morgan','Taylor','mtaylor@univ.edu',2020,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Kendall','Allen','kallen2@univ.edu',2021,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Avery','Harris','aharris@univ.edu',2025,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jordan','Brown','jbrown@univ.edu',2024,5);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jordan','Smith','jsmith@univ.edu',2023,3);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jamie','Thomas','jthomas@univ.edu',2025,9);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Skyler','Walker','swalker@univ.edu',2018,2);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Taylor','Anderson','tanderson@univ.edu',2018,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Reagan','Walker','rwalker@univ.edu',2020,7);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Riley','Johnson','rjohnson@univ.edu',2022,6);
INSERT INTO students (first_name, last_name, email, enrollment_year, major_department_id) VALUES ('Jordan','Garcia','jgarcia@univ.edu',2021,4);

INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT499','Systems in Physics',2,13,5,'Winter',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PHY311','Intro in Analysis',3,11,4,'Summer',2025);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO181','Advanced in Quantum',4,7,2,'Summer',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO279','Lab in Chemistry',4,7,3,'Winter',2019);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO268','Lab in Chemistry',4,7,2,'Spring',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ENG447','Systems in Biology',9,42,2,'Fall',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PHY119','Advanced in Neuroscience',3,37,5,'Spring',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ECO410','Systems in Data',6,31,5,'Winter',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('COM100','Systems in Physics',1,43,3,'Spring',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT269','Methods in Biology',2,30,2,'Spring',2023);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('CHE309','Foundations in Quantum',5,45,4,'Winter',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('HIS294','Topics in Neuroscience',7,41,4,'Summer',2023);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('COM246','Seminar in Quantum',1,28,4,'Summer',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY361','Theory in History',8,15,3,'Fall',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ENG147','Seminar in Statistics',9,34,4,'Winter',2025);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO112','Intro in Modeling',4,5,5,'Fall',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('HIS394','Seminar in Writing',7,41,5,'Summer',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO435','Intro in Physics',4,5,2,'Summer',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PHY125','Systems in Modeling',3,39,2,'Summer',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY486','Theory in Neuroscience',8,26,5,'Summer',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY232','Seminar in Chemistry',8,26,4,'Summer',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO325','Advanced in Writing',4,7,4,'Winter',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ECO376','Advanced in Analysis',6,29,3,'Winter',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PHY132','Applied in Quantum',3,11,4,'Summer',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('COM315','Applied in Physics',1,19,2,'Summer',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('COM252','Applied in Chemistry',1,28,5,'Winter',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO323','Theory in Algorithms',4,7,5,'Spring',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('HIS184','Theory in Physics',7,41,3,'Fall',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('STA439','Intro in Data',10,40,5,'Winter',2025);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY125','Lab in Quantum',8,15,4,'Winter',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ECO489','Applied in Design',6,29,5,'Spring',2025);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT109','Systems in Algorithms',2,20,4,'Winter',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT433','Intro in History',2,38,2,'Winter',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('COM222','Topics in Literature',1,19,2,'Winter',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('CHE185','Methods in Neuroscience',5,17,2,'Winter',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT113','Lab in Neuroscience',2,24,5,'Summer',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO403','Seminar in Data',4,5,4,'Fall',2025);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('STA277','Systems in Quantum',10,6,4,'Fall',2023);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ECO315','Theory in Data',6,22,5,'Spring',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY322','Topics in Writing',8,15,4,'Summer',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('HIS403','Lab in Biology',7,41,3,'Fall',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY484','Theory in Neuroscience',8,15,5,'Spring',2019);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY193','Theory in Modeling',8,26,4,'Spring',2021);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('CHE459','Lab in Econometrics',5,44,2,'Winter',2019);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO308','Theory in Econometrics',4,8,3,'Summer',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY108','Advanced in Design',8,26,3,'Summer',2024);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('BIO439','Methods in Biology',4,7,5,'Spring',2022);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('ENG280','Theory in Design',9,34,4,'Spring',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('MAT198','Foundations in Data',2,30,3,'Winter',2020);
INSERT INTO courses (code, title, department_id, professor_id, credits, term, year) VALUES ('PSY470','Methods in History',8,26,4,'Fall',2025);

INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (13,19,'2023-12-09','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (1,46,'2024-05-14','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,4,'2024-05-24','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,49,'2024-04-22','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (1,37,'2024-01-07','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,12,'2023-09-10','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,5,'2024-03-07','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,44,'2023-09-11','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (52,37,'2024-01-17','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (16,8,'2024-05-26','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,40,'2023-12-08','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,29,'2024-01-14','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (20,37,'2024-06-27','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,7,'2023-11-29','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (43,6,'2023-11-03','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,11,'2023-08-16','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (31,19,'2023-08-31','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (45,30,'2023-09-20','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,41,'2024-06-11','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (28,8,'2024-05-19','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,18,'2023-10-26','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (11,20,'2024-06-14','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,19,'2024-03-26','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (45,20,'2024-08-07','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,35,'2024-04-23','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,28,'2024-01-27','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,15,'2024-07-25','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (38,2,'2024-07-24','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,49,'2023-11-12','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (12,38,'2024-03-25','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,31,'2024-02-09','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (43,7,'2023-11-05','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,43,'2024-03-07','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,30,'2023-09-29','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,50,'2024-03-08','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (43,35,'2024-04-07','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,24,'2024-06-28','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,4,'2023-11-27','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (60,19,'2024-03-26','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,2,'2024-07-02','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (46,11,'2024-01-21','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (27,6,'2023-12-08','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,8,'2024-04-07','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,10,'2024-04-26','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,33,'2024-08-10','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (31,16,'2024-04-04','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (13,39,'2024-05-01','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,5,'2024-01-03','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,33,'2023-12-29','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (47,20,'2024-06-10','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,10,'2024-03-30','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,36,'2024-05-19','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,13,'2024-08-06','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,50,'2024-03-12','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,31,'2024-08-10','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,25,'2024-07-19','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (32,3,'2023-10-18','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,7,'2024-03-27','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,30,'2023-08-22','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,42,'2023-11-02','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,17,'2024-02-04','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,6,'2024-01-30','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,21,'2024-06-30','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,35,'2023-09-02','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,48,'2023-09-30','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,41,'2024-08-09','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (11,45,'2024-01-15','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,21,'2023-09-12','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (28,10,'2023-12-18','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (44,12,'2023-11-10','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (40,25,'2024-06-27','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,38,'2023-10-27','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (30,17,'2024-07-21','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (52,30,'2024-01-09','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,29,'2024-02-07','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (20,41,'2024-03-19','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,20,'2023-11-24','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,31,'2023-10-08','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,37,'2024-01-13','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,2,'2024-07-17','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,44,'2023-09-09','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,32,'2024-01-08','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,23,'2023-12-05','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (17,44,'2024-07-17','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,7,'2024-07-01','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,29,'2023-09-01','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,19,'2024-01-29','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (13,9,'2024-05-17','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,33,'2024-01-01','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,31,'2024-01-13','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (52,8,'2024-04-10','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,49,'2023-12-08','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,36,'2024-02-18','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,1,'2023-12-28','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (24,44,'2024-07-24','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (53,41,'2024-02-21','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,31,'2023-08-27','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,40,'2023-12-06','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,45,'2024-01-16','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (9,3,'2023-09-03','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,7,'2023-12-13','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,30,'2024-02-20','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (27,38,'2023-11-02','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (54,32,'2024-06-25','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,45,'2024-02-20','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,16,'2024-02-16','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (44,24,'2024-05-19','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,23,'2023-09-15','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,30,'2023-09-30','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,4,'2024-02-01','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,37,'2023-11-28','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,36,'2023-11-29','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,50,'2023-10-29','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (1,18,'2023-10-28','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (35,17,'2023-11-12','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,2,'2023-10-21','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,16,'2024-06-11','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (17,4,'2023-10-18','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,48,'2023-09-16','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,38,'2023-10-09','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (40,3,'2024-07-17','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,2,'2023-09-15','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,26,'2024-03-20','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (46,29,'2023-09-21','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,39,'2023-10-29','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (18,40,'2024-07-04','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,39,'2024-05-12','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,28,'2023-10-04','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,42,'2024-07-13','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (47,14,'2024-03-22','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (27,22,'2024-04-03','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,28,'2024-01-22','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,44,'2024-04-13','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (54,6,'2023-10-01','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (52,9,'2024-05-25','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,36,'2024-01-30','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,43,'2024-03-18','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,39,'2024-01-21','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,14,'2023-11-02','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,7,'2024-02-10','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,49,'2024-01-04','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,40,'2024-06-24','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,39,'2024-07-16','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,12,'2024-01-01','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,22,'2024-02-10','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,43,'2024-03-07','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,41,'2023-08-30','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,14,'2024-02-23','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (11,24,'2024-01-21','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,6,'2023-09-10','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,40,'2023-09-09','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,43,'2024-03-19','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (27,18,'2023-12-03','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,28,'2023-10-10','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (32,34,'2024-07-21','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,39,'2023-09-12','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (20,14,'2023-10-24','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,8,'2023-08-18','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (12,9,'2024-02-25','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,36,'2024-07-22','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,48,'2023-09-05','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,5,'2024-01-22','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,46,'2024-07-07','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,2,'2024-01-28','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (40,30,'2024-08-02','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,28,'2023-10-08','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,34,'2023-09-24','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,22,'2023-12-06','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,33,'2024-07-04','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,13,'2024-02-09','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (16,7,'2023-10-28','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,10,'2024-07-15','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,41,'2024-04-23','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,38,'2024-03-31','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,41,'2024-06-29','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,29,'2023-09-18','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,18,'2024-06-12','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,5,'2024-01-20','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (4,24,'2024-01-08','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,6,'2024-06-24','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (30,38,'2024-05-24','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,3,'2024-04-01','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,42,'2023-11-19','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,10,'2023-09-15','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (46,6,'2024-04-29','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (16,46,'2024-03-26','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,34,'2024-06-22','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (24,19,'2024-02-29','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (44,39,'2023-09-10','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,22,'2023-10-02','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,17,'2024-07-16','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,6,'2024-06-08','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (20,42,'2024-08-06','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,46,'2023-09-27','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,22,'2023-10-19','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,42,'2024-07-23','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,24,'2024-01-20','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (14,22,'2024-04-19','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (9,10,'2023-09-23','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,50,'2024-05-17','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,43,'2024-02-03','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (9,39,'2024-02-23','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (12,45,'2024-06-29','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (47,29,'2023-09-06','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,40,'2024-01-07','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,35,'2023-12-15','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (58,13,'2024-02-19','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,30,'2024-01-06','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,27,'2023-11-05','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (9,17,'2023-09-10','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,7,'2024-08-13','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,6,'2023-11-05','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,28,'2023-09-30','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,29,'2024-02-09','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (27,4,'2024-03-04','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,6,'2024-02-22','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (60,7,'2024-08-14','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,31,'2024-08-05','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (1,6,'2023-08-24','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,47,'2024-06-21','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,19,'2023-12-14','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (16,27,'2024-07-07','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,8,'2024-04-26','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,33,'2024-06-04','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,28,'2023-08-15','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,27,'2023-11-18','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (5,34,'2024-05-19','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,2,'2024-03-01','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,25,'2024-02-22','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,5,'2024-02-07','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,38,'2024-02-01','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,35,'2024-02-04','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (54,50,'2024-07-30','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,12,'2023-10-23','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,30,'2023-09-02','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,13,'2023-09-05','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,26,'2024-05-19','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,42,'2023-11-20','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,18,'2023-10-17','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (57,26,'2024-03-27','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (25,22,'2023-11-18','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (24,34,'2023-12-29','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,12,'2024-05-20','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,21,'2024-07-18','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (28,11,'2024-08-02','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,47,'2024-02-11','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (18,41,'2023-09-13','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (41,26,'2024-02-17','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,10,'2024-06-21','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (3,9,'2023-09-18','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (24,25,'2024-05-31','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (29,24,'2024-02-21','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,9,'2024-05-12','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,18,'2023-12-20','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (2,48,'2023-11-18','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (59,36,'2023-10-14','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (14,40,'2024-01-08','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (13,8,'2023-10-23','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (12,46,'2024-03-29','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (52,44,'2024-01-25','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,35,'2024-01-10','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,11,'2024-08-13','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,24,'2024-05-01','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (51,9,'2023-12-14','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (24,36,'2024-06-03','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (9,40,'2023-09-28','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (47,31,'2024-05-10','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (53,37,'2023-09-21','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,42,'2023-09-21','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (23,9,'2024-05-23','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (50,9,'2024-03-23','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (54,8,'2024-05-06','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (11,11,'2024-01-27','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (15,23,'2024-05-06','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (55,6,'2023-12-21','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,18,'2023-10-18','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (35,6,'2024-04-28','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (38,10,'2023-11-10','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (22,37,'2023-09-05','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (6,3,'2024-07-08','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (42,14,'2024-06-02','completed','A');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (32,41,'2024-05-20','completed','B-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,20,'2024-04-03','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (4,11,'2024-03-27','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,46,'2024-01-25','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,9,'2024-02-20','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,16,'2024-04-09','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,7,'2023-09-09','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (56,40,'2024-03-16','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (53,21,'2024-06-05','completed','B');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (49,11,'2024-04-26','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (30,32,'2024-01-19','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (26,33,'2024-04-05','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (14,38,'2024-02-11','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,32,'2024-06-15','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (19,35,'2023-08-19','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (47,24,'2024-03-08','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (4,37,'2024-05-28','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,19,'2023-09-21','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (44,40,'2023-10-14','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (7,26,'2024-02-22','completed','C+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (36,24,'2023-10-27','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (33,3,'2023-09-07','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (46,22,'2024-04-13','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (39,33,'2023-10-25','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (21,11,'2024-03-03','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (48,20,'2024-06-13','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (35,32,'2024-08-11','completed','C-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (53,2,'2024-02-19','completed','A-');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (20,47,'2024-08-01','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (31,17,'2024-07-15','completed','F');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (37,15,'2023-09-10','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (34,41,'2024-06-27','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (16,3,'2024-06-03','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (8,13,'2023-08-24','completed','C');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (10,27,'2024-08-02','enrolled',NULL);
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (40,31,'2023-09-15','completed','D');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (14,36,'2024-01-28','dropped','W');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (31,34,'2024-02-23','completed','B+');
INSERT INTO enrollments (student_id, course_id, enrolled_on, status, grade) VALUES (30,35,'2024-02-06','completed','B-');